Artsofte.Test/Areas/Team/Controllers/DepartmentsController.cs
using Artsofte.Test.Areas.Team.Models;
using Artsofte.Test.Models.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Artsofte.Test.Areas.Team.Controllers
{
    public class DepartmentsController : Controller
    {
        // GET: Team/Departments
        public ActionResult List()
        {
            var context = DataContext.JoinOrCreate();

            var departments = context.Departments
                .OrderBy(x => x.Title);

            return View(departments);
        }

        [HttpGet]
        public ActionResult Add()
        {
            var model = new Department()
            {
                Id = Guid.NewGuid()
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Add(FormCollection collection)
        {
            var context = DataContext.JoinOrCreate();
            var model = new Department();

            TryUpdateModel(model);
            if (!ModelState.IsValid)
                return View(model);

            context.Departments.Add(model);
            context.SaveChanges();

            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var context = DataContext.JoinOrCreate();

            var model = context.Departments.Find(id);
            if (model == null)
                return HttpNotFound();

            return View(model);
        }

        public ActionResult Edit(Guid id, FormCollection collection)
        {
            var context = DataContext.JoinOrCreate();

            var model = context.Departments.Find(id);
            if (model == null)
                return HttpNotFound();

            TryUpdateModel(model, collection);

            if (!ModelState.IsValid)
                return View(model);


            context.SaveChanges();

            return RedirectToAction("List");
        }

        public ActionResult Delete(Guid id)
        {
            var context = DataContext.JoinOrCreate();

            var model = context.Departments.Find(id);
            if (model == null)
                return HttpNotFound();

            context.Departments.Remove(model);
            context.SaveChanges();

            return RedirectToAction("List");
        }
    }
}

Artsofte.Test/Areas/Team/Views/Departments/Add.cshtml
@model Artsofte.Test.Areas.Team.Models.Department

@{
    ViewBag.Title = "Добавить";
}

<h2>Добавить</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Отдел</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Floor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Floor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Floor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
                @Html.HiddenFor(x => x.Id)
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "List", "Departments", new { area = "Team" }, null)
</div>

Artsofte.Test/Areas/Team/Views/Departments/Edit.cshtml
@model Artsofte.Test.Areas.Team.Models.Department

@{
    ViewBag.Title = "Редактировать";
}

<h2>Редактировать</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Отдел</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Floor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Floor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Floor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "List", "Departments", new { area = "Team" }, null)
</div>

Artsofte.Test/Areas/Team/Views/Departments/List.cshtml
@model IEnumerable<Artsofte.Test.Areas.Team.Models.Department>

@{
    ViewBag.Title = "Отделы";
}

<h2>Отделы</h2>

<p>
    @Html.ActionLink("Создать новый", "Add", "Departments", new { area = "Team" }, null)
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Floor)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Floor)
            </td>
            <td>
                @Html.ActionLink("Редактировать", "Edit", "Departments", new { id = item.Id }, null) |
                @Html.ActionLink("Удалить", "Delete", "Departments", new { id = item.Id }, null)
            </td>
        </tr>
    }

</table>