Artsofte.Test/Areas/Team/Models/Employee.cs
using Artsofte.Test.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Artsofte.Test.Areas.Team.Models
{
    public class Employee : Entity
    {
        [Display(Name = "Имя")]
        [Required]
        public string Name { get; set; }

        [Display(Name = "Фамилия")]
        [Required]
        public string SecondName { get; set; }

        [Display(Name = "Возраст")]
        [Required]
        public int Age { get; set; }

        [Display(Name = "Пол")]
        [Required]
        public string Gender { get; set; }

        [Display(Name = "Департамент")]
        public virtual Department Department { get; set; }

        public Guid DepartmentId { get; set; }

        [Display(Name = "Язык программирования")]
        public virtual ProgrammingLanguage Language { get; set; }

        public Guid LanguageId { get; set; }


        public override string ToString()
        {
            return string.Format("{0}={1}", Name, Id);
        }
    }
}

Artsofte.Test/Areas/Team/Controllers/AjaxController.cs
using Artsofte.Test.Models.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Artsofte.Test.Areas.Team.Controllers
{
    public class AjaxController : Controller
    {
        // GET: Team/Ajax
        public ActionResult Names(string term)
        {
            var context = DataContext.JoinOrCreate();

            var names = context.Names
                .Where(x => x.Title.Contains(term))
                .OrderBy(x => x.Title)
                .Select(x => x.Title);

            return Json(names, JsonRequestBehavior.AllowGet);
        }
    }
}

Artsofte.Test/Areas/Team/Controllers/EmployeesController.cs
using Artsofte.Test.Areas.Team.Models;
using Artsofte.Test.Models.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Artsofte.Test.Code.Extensions;
using System.Diagnostics;

namespace Artsofte.Test.Areas.Team.Controllers
{
    public class EmployeesController : Controller
    {
        public ActionResult List()
        {
            var context = DataContext.JoinOrCreate();

            var employees = context.Employees
                .OrderBy(x => x.Name);

            return View(employees);
        }

        [HttpGet]
        public ActionResult Add()
        {
            var employee = new Employee()
            {
                Id = Guid.NewGuid()
            };

            return View(employee);
        }

        [HttpPost]
        public ActionResult Add(FormCollection collection)
        {
            var context = DataContext.JoinOrCreate();
            var model = new Employee();

            TryUpdateModel(model, collection);

            if (!ModelState.IsValid)
                return View(model);

            context.Employees.Add(model);
            context.SaveChanges();

            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var context = DataContext.JoinOrCreate();

            var model = context.Employees.Find(id);
            if (model == null)
                return HttpNotFound();

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Guid id, FormCollection collection)
        {
            var context = DataContext.JoinOrCreate();
            var model = context.Employees.Find(id);
            if (model == null)
                return HttpNotFound();

            TryUpdateModel(model, collection);

            if (!ModelState.IsValid)
            {
                context.Rollback();
                return View(model);
            }

            context.SaveChanges();

            return RedirectToAction("List");
        }

        public ActionResult Delete(Guid id)
        {
            var context = DataContext.JoinOrCreate();

            var model = context.Employees.Find(id);
            if (model == null)
                return HttpNotFound();

            context.Employees.Remove(model);
            context.SaveChanges();

            return RedirectToAction("List");
        }

        public ActionResult Detail(Guid id)
        {
            var context = DataContext.JoinOrCreate();

            var model = context.Employees.Find(id);
            if (model == null)
                return HttpNotFound();

            return View(model);
        }
    }
}

Artsofte.Test/Areas/Team/Views/Employees/Add.cshtml
@model Artsofte.Test.Areas.Team.Models.Employee

@{
    ViewBag.Title = "Добавить";
}

<h2>Добавить</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Сотрудник</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecondName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecondName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecondName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Gender, TeamDictionary.Gender(Model.Gender), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.DepartmentId, TeamDictionary.Departments(Model.Language), "-== выбрать ==-", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Language, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.LanguageId, TeamDictionary.ProgrammingLanguages(Model.Language), "-== выбрать ==-", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Language, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
                @Html.HiddenFor(x => x.Id)
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "List", "Employees", new { area = "Team" }, null)
</div>


@section Body
{
    <script type="text/javascript">
        $('#Name').autocomplete({
            source: "@Url.Action("Names", "Ajax", new { area = "Team" })",
            minLenght: 2
        })
    </script>
}

Artsofte.Test/Areas/Team/Views/Employees/Detail.cshtml
@model Artsofte.Test.Areas.Team.Models.Employee

@{
    ViewBag.Title = "Описание";
}

<h2>Описание</h2>

<div>
    <h4>Сотрудник</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Language)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Language.Title)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", "Employees", new { id = Model.Id , area = "Team" }, null) |
    @Html.ActionLink("Назад", "List", "Employees", new { area = "Team" }, null)
</p>

Artsofte.Test/Areas/Team/Views/Employees/Edit.cshtml
@model Artsofte.Test.Areas.Team.Models.Employee

@{
    ViewBag.Title = "Редактировать";
}

<h2>Редактировать</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Сотрудник</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecondName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecondName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecondName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Gender, TeamDictionary.Gender(Model.Gender), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.DepartmentId, TeamDictionary.Departments(Model.DepartmentId), "-== выбрать ==-", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Language, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.LanguageId, TeamDictionary.ProgrammingLanguages(Model.LanguageId), "-== выбрать ==-", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Language, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "List", "Employees", new { area = "Team" }, null)
</div>

@section Body
{
    <script type="text/javascript">
        $('#Name').autocomplete({
            source: "@Url.Action("Names", "Ajax", new { area = "Team" })",
            minLenght: 2
        })
    </script>
}

Artsofte.Test/Areas/Team/Views/Employees/List.cshtml
@model IEnumerable<Employee>

@{
    ViewBag.Title = "Сотрудники";
}

<h2>Сотрудники</h2>

<p>
    @Html.ActionLink("Добавить", "Add")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SecondName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SecondName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.ActionLink("Редактировать", "Edit", "Employees", new { id = item.Id }, null) |
            @Html.ActionLink("Описание", "Detail", "Employees", new { id = item.Id }, null) |
            @Html.ActionLink("Удалить", "Delete", "Employees", new { id = item.Id }, null)
        </td>
    </tr>
}

</table>