Artsofte.Test/Areas/Team/Models/ProgrammingLanguage.cs
using Artsofte.Test.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Artsofte.Test.Areas.Team.Models
{
    public class ProgrammingLanguage : Entity
    {
        [Display(Name = "Название")]
        [Required]
        public string Title { get; set; }

        public virtual ICollection<Employee> Employees { get; set; }

        public override string ToString()
        {
            return string.Format("{0}={1}", Title, Id);
        }
    }
}

Artsofte.Test/Areas/Team/Controllers/ProgrammingLanguagesController.cs
using Artsofte.Test.Areas.Team.Models;
using Artsofte.Test.Models.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Artsofte.Test.Areas.Team.Controllers
{
    public class ProgrammingLanguagesController : Controller
    {
        // GET: Team/ProgrammingLanguages
        public ActionResult List()
        {
            var context = DataContext.JoinOrCreate();

            var languages = context.Languages
                .OrderBy(x => x.Title);

            return View(languages);
        }

        [HttpGet]
        public ActionResult Add()
        {
            var model = new ProgrammingLanguage()
            {
                Id = Guid.NewGuid()
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Add(FormCollection collection)
        {
            var context = DataContext.JoinOrCreate();
            var model = new ProgrammingLanguage();

            TryUpdateModel(model);
            if (!ModelState.IsValid)
                return View(model);

            context.Languages.Add(model);
            context.SaveChanges();

            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var context = DataContext.JoinOrCreate();

            var model = context.Languages.Find(id);
            if (model == null)
                return HttpNotFound();

            return View(model);
        }

        public ActionResult Edit(Guid id, FormCollection collection)
        {
            var context = DataContext.JoinOrCreate();

            var model = context.Languages.Find(id);
            if (model == null)
                return HttpNotFound();

            TryUpdateModel(model, collection);

            if (!ModelState.IsValid)
                return View(model);


            context.SaveChanges();

            return RedirectToAction("List");
        }

        public ActionResult Delete(Guid id)
        {
            var context = DataContext.JoinOrCreate();

            var model = context.Languages.Find(id);
            if (model == null)
                return HttpNotFound();

            context.Languages.Remove(model);
            context.SaveChanges();

            return RedirectToAction("List");
        }
    }
}

Artsofte.Test/Areas/Team/Views/ProgrammingLanguages/Add.cshtml
@model Artsofte.Test.Areas.Team.Models.ProgrammingLanguage

@{
    ViewBag.Title = "Создать";
}

<h2>Создать</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Язык программирования</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
                @Html.HiddenFor(x => x.Id)
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "List", "ProgrammingLanguages", new { area = "Team" }, null)
</div>

Artsofte.Test/Areas/Team/Views/ProgrammingLanguages/Edit.cshtml
@model Artsofte.Test.Areas.Team.Models.ProgrammingLanguage

@{
    ViewBag.Title = "Редактировать";
}

<h2>Редактировать</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Язык программирования</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "List", "ProgrammingLanguages", new { area = "Team" }, null)
</div>

Artsofte.Test/Areas/Team/Views/ProgrammingLanguages/List.cshtml
@model IEnumerable<Artsofte.Test.Areas.Team.Models.ProgrammingLanguage>

@{
    ViewBag.Title = "Языки программирования";
}

<h2>Языки программирования</h2>

<p>
    @Html.ActionLink("Создать новый", "Add", "ProgrammingLanguages", new { area = "Team" }, null)
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.ActionLink("Редактировать", "Edit", "ProgrammingLanguages", new { id = item.Id }, null) |
            @Html.ActionLink("Удалить", "Delete", "ProgrammingLanguages", new { id = item.Id }, null)
        </td>
    </tr>
}
</table>