Artsofte.Test/Areas/Team/Models/Name.cs
using Artsofte.Test.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Artsofte.Test.Areas.Team.Models
{
    public class Name : Entity
    {
        [Display(Name = "Имя")]
        [Required]
        public  string Title { get; set; }
    }
}

Artsofte.Test/Areas/Team/Controllers/NamesController.cs
using Artsofte.Test.Areas.Team.Models;
using Artsofte.Test.Models.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Artsofte.Test.Areas.Team.Controllers
{
    public class NamesController : Controller
    {
        public ActionResult List()
        {
            var context = DataContext.JoinOrCreate();

            var names = context.Names
                .OrderBy(x => x.Title);

            return View(names);
        }

        [HttpGet]
        public ActionResult Add()
        {
            var model = new Name()
            {
                Id = Guid.NewGuid()
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Add(FormCollection collection)
        {
            var context = DataContext.JoinOrCreate();
            var model = new Name();

            TryUpdateModel(model);
            if (!ModelState.IsValid)
                return View(model);

            context.Names.Add(model);
            context.SaveChanges();

            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var context = DataContext.JoinOrCreate();

            var model = context.Names.Find(id);
            if (model == null)
                return HttpNotFound();

            return View(model);
        }

        public ActionResult Edit(Guid id, FormCollection collection)
        {
            var context = DataContext.JoinOrCreate();

            var model = context.Names.Find(id);
            if (model == null)
                return HttpNotFound();

            TryUpdateModel(model, collection);

            if (!ModelState.IsValid)
                return View(model);


            context.SaveChanges();

            return RedirectToAction("List");
        }

        public ActionResult Delete(Guid id)
        {
            var context = DataContext.JoinOrCreate();

            var model = context.Names.Find(id);
            if (model == null)
                return HttpNotFound();

            context.Names.Remove(model);
            context.SaveChanges();

            return RedirectToAction("List");
        }
    }
}

Artsofte.Test/Areas/Team/Views/Names/Add.cshtml
@model Artsofte.Test.Areas.Team.Models.Name

@{
    ViewBag.Title = "Имена";
}

<h2>Добавить</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Имя</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
                @Html.HiddenFor(x => x.Id)
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "List", "Names", new { area = "Team" }, null)
</div>

Artsofte.Test/Areas/Team/Views/Names/Edit.cshtml
@model Artsofte.Test.Areas.Team.Models.Name

@{
    ViewBag.Title = "Редактировать";
}

<h2>Редактировать</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Имя</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "List", "Names", new { area = "Team" }, null)
</div>

Artsofte.Test/Areas/Team/Views/Names/List.cshtml
@model IEnumerable<Artsofte.Test.Areas.Team.Models.Name>

@{
    ViewBag.Title = "Имена";
}

<h2>Имена</h2>

<p>
    @Html.ActionLink("Добавить", "Add")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.ActionLink("Редактировать", "Edit", "Names", new { id = item.Id }, null) |
            @Html.ActionLink("Удалить", "Delete", "Names", new { id = item.Id }, null)
        </td>
    </tr>
}

</table>